// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Article: typeof import("./src/components/Article.vue")["default"];
    Comment: typeof import("./src/components/Comment.vue")["default"];
    DisplaySanbox: typeof import("./src/components/DisplaySanbox.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    Header: typeof import("./src/components/Header.vue")["default"];
    Notice: typeof import("./src/components/Notice.vue")["default"];
    Page: typeof import("./src/components/Page.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Side: typeof import("./src/components/Side.vue")["default"];
    Tail: typeof import("./src/components/Tail.vue")["default"];
  }
}
